apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello
  annotations:
    argocd-image-updater.argoproj.io/image-list: hello=registry.orb.local/hello-http
    argocd-image-updater.argoproj.io/hello.update-strategy: semver
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/cheleb/hello-argocd.git
    targetRevision: main
    path: environments/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: hello
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=Foreground
      - PruneLast=true
