apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-http
spec:
  selector:
    matchLabels:
      app: hello-http
  template:
    metadata:
      labels:
        app: hello-http
    spec:
      containers:
        - name: hello-http
          image: registry.orb.local/hello-http
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          imagePullPolicy: IfNotPresent
          ports:
            - name: hello-http-port
              containerPort: 8000
          env:
            - name: DB_HOST
              value: postgresql-svc
            - name: POSTGRES_USERNAME
              value: test
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-secrets
                  key: POSTGRES_PASSWORD
