---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: hello
  namespace: hello
resources:
  - namespace.yaml
  - postgresql.yaml
  - postgresql-svc.yaml
  - hello-http.yaml
  - hello-http-svc.yaml
